 const VisitorData = [
    {
      id: 1,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "-",
      Time_Out: "-",
    },
    {
      id: 2,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 3,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 4,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 5,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 6,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 7,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 8,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 9,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 10,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 11,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 12,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 13,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 14,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 15,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 16,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 17,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 18,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 19,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 20,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 21,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 22,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 23,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 24,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 25,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 26,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 27,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 28,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed Out",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 29,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 30,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 31,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 32,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 33,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 34,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 35,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Signed In",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
    {
      id: 36,
      Name: "Adeyemo Olayemi",
      Phone_Number: "000 0000 000",
      PurposeOfVisit: "Social Visit",
      AccessStatus: "Pending",
      DateOfVisit: "4th January, 2024",
      AccessCode: "VictorKunle-3096",
      No_Of_Persons: "5",
      TimeIn: "2:05 PM",
      Time_Out: "5:05 PM",
    },
  ];

  export default VisitorData;