const { default: NotiTenant } = require("@/components/icons/notiTenant");

const notificationsData = [
  {
    id: 1,
    subject: "Rent Information Update",
    message: "Your rent amount was updated to [New Rent Amount].",
    action: "Review details",
    date: "September 20, 2024",
    image: <NotiTenant />,
    time: "11:30 AM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 2,
    subject: "Property Information Update",
    message: "Property Address was updated to [New Property Address].",
    action: null,
    date: "September 20, 2024",
    image: <NotiTenant />,
    time: "11:30 AM",
    status: "unread",
    type: "Property Updates",
    createdAt: "2024-09-20T11:30:00Z",
  },
  {
    id: 3,
    subject: "Rent Information Update",
    message: "Your rent payment for [Rent Start Date] to [Rent Due Date] was confirmed.",
    action: "Review payment details.",
    date: "September 21, 2024",
    image: <NotiTenant />,
    time: "10:45 AM",
    status: "read",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 4,
    subject: "Property Information Update",
    message: "Manager's contact was updated to [New Manager's Contact Name].",
    action: null,
    date: "September 21, 2024",
    image: <NotiTenant />,
    time: "10:30 AM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
  {
    id: 5,
    subject: "Property Information Update",
    message: "Property Address for [Property Name] was updated to [New Property Address].",
    action: null,
    date: "September 22, 2024",
    image: <NotiTenant />,
    time: "09:15 AM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-20T11:30:00Z",
  },
  {
    id: 6,
    subject: "Property Information Update",
    message: "Property Name for [Old Property Name] was updated to [New Property Name].",
    action: null,
    date: "September 24, 2024",
    image: <NotiTenant />,
    time: "08:20 AM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 7,
    subject: "Rent Cashback!",
    message: "You received a cashback on your last rent payment.",
    action: null,
    date: "September 24, 2024",
    image: <NotiTenant />,
    time: "08:00 AM",
    status: "read",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:30:00Z",
  },
  {
    id: 8,
    subject: "Rent Information Update",
    message: "Your rent was increased by 5%.",
    action: "Review details",
    date: "September 25, 2024",
    image: <NotiTenant />,
    time: "09:00 AM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 9,
    subject: "Property Information Update",
    message: "The property manager's email was updated to [New Manager Email].",
    action: null,
    date: "September 25, 2024",
    image: <NotiTenant />,
    time: "08:30 AM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 10,
    subject: "Rent Cashback!",
    message: "You received a cashback reward on your rent.",
    action: null,
    date: "September 24, 2024",
    image: <NotiTenant />,
    time: "03:15 PM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:30:00Z",
  },
  {
    id: 11,
    subject: "Property Information Update",
    message: "The property's contact details have been updated.",
    action: null,
    date: "September 25, 2024",
    image: <NotiTenant />,
    time: "12:45 PM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-20T11:30:00Z",
  },
  {
    id: 12,
    subject: "Rent Information Update",
    message: "Your rent payment for [Rent Start Date] to [Rent Due Date] was confirmed.",
    action: "Review payment details.",
    date: "September 26, 2024",
    image: <NotiTenant />,
    time: "11:00 AM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-21T10:30:00Z",
  },
  {
    id: 13,
    subject: "Property Information Update",
    message: "A new property has been assigned to you.",
    action: null,
    date: "September 26, 2024",
    image: <NotiTenant />,
    time: "10:30 AM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-21T10:45:00Z",
  },
  {
    id: 14,
    subject: "Rent Information Update",
    message: "Your rent payment for this month is overdue.",
    action: "Review details",
    date: "September 27, 2024",
    image: <NotiTenant />,
    time: "02:15 PM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
  {
    id: 15,
    subject: "Rent Cashback!",
    message: "You received a cashback on your rent payment.",
    action: null,
    date: "September 27, 2024",
    image: <NotiTenant />,
    time: "01:00 PM",
    status: "read",
    type: "Rent Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
  {
    id: 16,
    subject: "Property Information Update",
    message: "Your property lease has been extended.",
    action: null,
    date: "September 27, 2024",
    image: <NotiTenant />,
    time: "03:45 PM",
    status: "unread",
    type: "Property Updates",
    createdAt: "2024-09-20T11:30:00Z",
  },
  {
    id: 17,
    subject: "Rent Information Update",
    message: "Your rent payment for [Rent Start Date] to [Rent Due Date] was confirmed.",
    action: "Review payment details.",
    date: "September 28, 2024",
    image: <NotiTenant />,
    time: "12:00 PM",
    status: "unread",
    type: "Rent Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
  {
    id: 18,
    subject: "Property Information Update",
    message: "The property's maintenance has been scheduled.",
    action: null,
    date: "September 28, 2024",
    image: <NotiTenant />,
    time: "02:00 PM",
    status: "read",
    type: "Property Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
  {
    id: 19,
    subject: "Rent Cashback!",
    message: "Your cashback for the rent has been applied.",
    action: null,
    date: "September 28, 2024",
    image: <NotiTenant />,
    time: "11:45 AM",
    status: "read",
    type: "Rent Updates",
    createdAt: "2024-09-20T11:30:00Z",
  },
  {
    id: 20,
    subject: "Property Information Update",
    message: "Property location updated to [New Location].",
    action: null,
    date: "September 29, 2024",
    image: <NotiTenant />,
    time: "04:00 PM",
    status: "unread",
    type: "Property Updates",
    createdAt: "2024-09-25T09:00:00Z",
  },
];

module.exports = notificationsData;
