export const Data = [
    {
      id: 1,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 2,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 3,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 4,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 5,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 6,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 7,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 8,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 9,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 10,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 11,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 12,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 13,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 14,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 15,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 16,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 17,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 18,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 19,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 20,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 21,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 22,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 23,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 24,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 25,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 26,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 27,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 28,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 29,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 30,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 31,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 32,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 33,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 34,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Paid",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 35,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Over Due",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
    {
      id: 36,
      Tenant: "Adeyemo Olayemi",
      Estate: "Sunrise Property",
      Rent: "N750,000",
      Status: "Pending",
      DueDate: "4th January, 2024",
      ApartmentNo: "Apartment1",
      Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
      Email: "AdeyemoOla@gmail.com",
      PhoneNo: "0801  000 0000",
    },
  ];

