export const Data = [
  {
    id: 1,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 2,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 3,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 4,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 5,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 6,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 7,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 8,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 9,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 10,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 11,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 12,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 13,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 14,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 15,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 16,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 17,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 18,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 19,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 20,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 21,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 22,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 23,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 24,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 25,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 26,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 27,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 28,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 29,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 30,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 31,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 32,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 33,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 34,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",

    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 35,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
  {
    id: 36,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
    Email: "AdeyemoOla@gmail.com",
    PhoneNo: "0801  000 0000",
    Action: "View visitor record",
  },
];
