export const Properties2 = [
    {
      _id: 1,
  
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 5,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment1.svg",
    otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 2,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Ajah",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/apartment2.svg",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
        ],
      },
    },
    {
      _id: 3,
      PropertyInfo: {
        Title: "Sunshine House",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Ikeja",
        PropertyAddress: "Onike Street",
        Bedrooms: 3,
        Bathroom: 2,
        Toilets: 1,
        Rating: 3,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment3.svg",
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
        ],
      },
    },
  
    {
      _id: 4,
      PropertyInfo: {
        Title: "Teddy Property",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Block of flats",
        Price: 106000,
        Area: "Victoria Island",
        PropertyAddress: "Onike Street",
        Bedrooms: 2,
        Bathroom: 7,
        Toilets: 1,
        Rating: 2,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
    otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/apartment2.svg",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 5,
  
      PropertyInfo: {
        Title: "Traos Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Boys Quarters",
        Price: 106000,
        Area: "Surulere",
        PropertyAddress: "Onike Street",
        Bedrooms: 2,
        Bathroom: 5,
        Toilets: 1,
        Rating: 5,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/house1.png",
          "/static/images/apartment2.svg",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 6,
      PropertyInfo: {
        Title: "Hazez",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Block of flats",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 5,
        Bathroom: 3,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment1.svg",
        otherPhotos: [
          "/static/images/apartment2.svg",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/apartment2.svg",
          "/static/images/house1.png",
        ],
      },
    },
    {
      _id: 7,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Semi-Detached Duplex",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 2,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment3.svg",
    otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
        ],
      },
    },
    {
      _id: 8,
      PropertyInfo: {
        Title: "Kratos",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Terraced Duplex",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 3,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 100000,
        maintenanceFee: 5000,
        totalFee: 10000,
        yearlyRent: 80000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/apartment2.svg",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/apartment2.svg",
        ],
      },
    },
    {
      _id: 9,
      PropertyInfo: {
        Title: "Pinky Estate",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 6,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
  
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          
        ],
      },
    },
    {
      _id: 10,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Terraced Duplex",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 3,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/imageHouseHP.png",
    otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 11,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Penthouse",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/house1.png",
          "/static/images/apartment2.svg",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 12,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/house2.png",
        otherPhotos: [
          "/static/images/apartment2.svg",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 13,
      PropertyInfo: {
        Title: "Ephratah",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Penthouse",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment3.svg",
    otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/apartment2.svg",
        ],
      },
    },
  
    {
      _id: 14,
      PropertyInfo: {
        Title: "Bethel Homez",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Penthouse",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 15,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Mini flat",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment1.svg",
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 16,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 1,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment3.svg",
    otherPhotos: [
          "/static/images/house1.png",
          "/static/images/apartment2.svg",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 17,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Mini flat",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 10,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment2.svg",
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
    {
      _id: 18,
      PropertyInfo: {
        Title: "Adex Aosz",
        State: "Lagos Island",
        Status: "For Rent",
        Property_type: "Studio Apartment",
        Price: 106000,
        Area: "Yaba",
        PropertyAddress: "Onike Street",
        Bedrooms: 7,
        Bathroom: 1,
        Toilets: 1,
        Rating: 4,
        Description: "Great, awesome and cool place to be",
      },
      contactInfo: {
        PhoneNumber: "09056432765",
        Email: "pinky@estate.com",
        WhatsAppLink: "whatsapp+2349065432786",
      },
      RentalInfo: {
        monthlyRent: 2000000,
        maintenanceFee: 10000,
        totalFee: 150000,
        yearlyRent: 680000000,
        agencyFee: 25000,
      },
      Photos: {
        coverPhoto: "/static/images/apartment1.svg",
        otherPhotos: [
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
          "/static/images/house1.png",
          "/static/images/imageHouseHP.png",
          "/static/images/house2.png",
        ],
      },
    },
  ];
  