export const Properties = [
  {
    _id: 1,
    image: [
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Boys Quarters",
    Price: 1000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "3 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 125,
    Rating: "3"
  },
  {
    _id: 2,
    image: [
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
    ],
    State: "Oyo",
    Status: "For Rent",
    Property_type: "Semi-Detached Duplex",
    Price: 101000000,
    Area: "VI Lagos",
    Bedrooms: "2 Bedrooms",
    Bathroom: "4 bathrooms",
    SqrTF: 110,
    Rating: "4"
  },
  {
    _id: 3,
    image: [
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
    ],
    State: "Lagos",
    Status: "For Sale",
    Property_type: "Terraced Bungalow",
    Price: 102000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "4 Bedrooms",
    Bathroom: "2 bathrooms",
    SqrTF: 120,
    Rating: "2"
  },

  {
    _id: 4,
    image: [
      "/static/images/apartment1.svg",
      "/static/images/apartment3.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment3.svg",
    ],
    State: "Abuja",
    Status: "For Rent",
    Property_type: "Detached Bungalow",
    Price: 203000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "5 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 130,
    Rating: "4"
  },
  {
    _id: 5,
    image: [
      "/static/images/apartment3.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Sale",
    Property_type: "Block of flats",
    Price: 104000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "6 Bedrooms",
    Bathroom: "2 bathrooms",
    SqrTF: 140,
    Rating: "3"
  },
  {
    _id: 6,
    image: [
      "/static/images/apartment2.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment3.svg",
      "/static/images/apartment2.svg",
      "/static/images/apartment3.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Studio Apartment",
    Price: 105000000,
    Area: "Onike, Ikeja, Lagos",
    Bedrooms: "1 Bedrooms",
    Bathroom: "1 bathrooms",
    SqrTF: 150,
    Rating: "4"
  },
  {
    _id: 7,
    image: [
      "/static/images/apartment1.svg",
      "/static/images/apartment1.svg",
      "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Self contain",
    Price: 1060000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "1 Bedrooms",
    Bathroom: "1 bathrooms",
    SqrTF: 160,
    Rating: "4"
  },
  {
    _id: 8,
    image: [
        "/static/images/apartment2.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Enugu",
    Status: "For Sale",
    Property_type: "Penthouse",
    Price: 507000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "3 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 170,
    Rating: "5"
  },
  {
    _id: 9,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Mini-flat",
    Price: 108000000,
    Area: "Ikeja, Lagos",
    Bedrooms: "2 Bedrooms",
    Bathroom: "2 bathrooms",
    SqrTF: 1300,
    Rating: "5"
  },
  {
    _id: 10,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Ajah",
    Status: "For Sale",
    Property_type: "Detached Duplex",
    Price: 309000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "4 Bedrooms",
    Bathroom: "4 bathrooms",
    SqrTF: 600,
    Rating: "4"
  },
  {
    _id: 11,
    image: [
        "/static/images/apartment3.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Boys Quarters",
    Price: 1000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "3 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 700,
    Rating: "2"
  },
  {
    _id: 12,
    image: [
        "/static/images/apartment2.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Kaduna",
    Status: "For Sale",
    Property_type: "Semi-Detached Duplex",
    Price: 1010000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "2 Bedrooms",
    Bathroom: "4 bathrooms",
    SqrTF: 1100,
    Rating: "5"
  },
  {
    _id: 13,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Ojodu",
    Status: "For Rent",
    Property_type: "Terraced Bungalow",
    Price: 2020000,
    Area: "Ojudu Lagos",
    Bedrooms: "4 Bedrooms",
    Bathroom: "2 bathrooms",
    SqrTF: 120,
    Rating: "2"
  },

  {
    _id: 14,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Detached Bungalow",
    Price: 1030000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "5 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 5000,
    Rating: "4"
  },
  {
    _id: 15,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Penthouse",
    Price: 104000,
    Area: "Ojudu, Lagos",
    Bedrooms: "4 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 1040,
    Rating: "4"
  },
  {
    _id: 16,
    image: [
        "/static/images/apartment3.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Sale",
    Property_type: "Mini-flat",
    Price: 105000000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "1 Bedrooms",
    Bathroom: "1 bathrooms",
    SqrTF: 1050,
    Rating: "5"
  },
  {
    _id: 17,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Rent",
    Property_type: "Studio Apartment",
    Price: 106000,
    Area: "Onike, Yaba, Lagos",
    Bedrooms: "1 Bedrooms",
    Bathroom: "1 bathrooms",
    SqrTF: 360,
    Rating: "4"
  },
  {
    _id: 18,
    image: [
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
        "/static/images/apartment3.svg",
        "/static/images/apartment1.svg",
        "/static/images/apartment2.svg",
    ],
    State: "Lagos",
    Status: "For Sale",
    Property_type: "Detached Duplex",
    Price: 107000,
    Area: "Island Lagos",
    Bedrooms: "4 Bedrooms",
    Bathroom: "3 bathrooms",
    SqrTF: 170,
    Rating: "4"
  },
];
