export const Properties = [
  {
    _id: 1,

    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 500,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Quarterly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment1.svg",
  otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 2,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Land",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Ajah",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Daily",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/apartment2.svg",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
      ],
    },
  },
  {
    _id: 3,
    PropertyInfo: {
      Name: "Sunshine House",
      Title: "Title",
      State: "Lagos",
      ListingType: "Sale",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Ikeja",
      Street: "Onike Street",
      Bedrooms: 3,
      Bathroom: 2,
      Toilets: 1,
      SquareMetres: 300,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Outright-Payment",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment3.svg",
      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
      ],
    },
  },

  {
    _id: 4,
    PropertyInfo: {
      Name: "Teddy Property",
      Title: "Title",
      State: "Lagos",
      ListingType: "Land",
      Property_type: "Block of flats",
      Price: 106000,
      Area: "Victoria",
      Street: "Onike Street",
      Bedrooms: 2,
      Bathroom: 7,
      Toilets: 1,
      SquareMetres: 200,
      LandType:"Industrial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Every_6_Months",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
  otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/apartment2.svg",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 5,

    PropertyInfo: {
      Name: "Traos Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Shortlet",
      Property_type: "Boys Quarters",
      Price: 106000,
      Area: "Surulere",
      Street: "Onike Street",
      Bedrooms: 2,
      Bathroom: 5,
      Toilets: 1,
      SquareMetres: 500,
      LandType:"Residential",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Daily",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/house1.png",
        "/static/images/apartment2.svg",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 6,
    PropertyInfo: {
      Name: "Hazez",
      Title: "Title",
      State: "Lagos",
      ListingType: "Land",
      Property_type: "Block of flats",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 5,
      Bathroom: 3,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Farmland",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Outright-Payment",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment1.svg",
      otherPhotos: [
        "/static/images/apartment2.svg",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/apartment2.svg",
        "/static/images/house1.png",
      ],
    },
  },
  {
    _id: 7,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Semi-Detached Duplex",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 2,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Mixed-Use",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Daily",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment3.svg",
  otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
      ],
    },
  },
  {
    _id: 8,
    PropertyInfo: {
      Name: "Kratos",
      Title: "Title",
      State: "Oyo",
      ListingType: "Sale",
      Property_type: "Terraced Duplex",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 3,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Mixed-Use",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 100000,
      maintenanceFee: 5000,
      totalFee: 10000,
      Payment_Type:"Monthly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/apartment2.svg",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/apartment2.svg",
      ],
    },
  },
  {
    _id: 9,
    PropertyInfo: {
      Name: "Pinky Estate",
      Title: "Title",
      State: "Lagos",
      ListingType: "Land",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 6,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Quarterly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",

      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        
      ],
    },
  },
  {
    _id: 10,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Oyo",
      ListingType: "Land",
      Property_type: "Terraced Duplex",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 3,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Monthly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/imageHouseHP.png",
  otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 11,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Calabar",
      ListingType: "Shortlet",
      Property_type: "Penthouse",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Farmland",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Every_6_Months",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/house1.png",
        "/static/images/apartment2.svg",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 12,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Calabar",
      ListingType: "Rent",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Monthly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/house2.png",
      otherPhotos: [
        "/static/images/apartment2.svg",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 13,
    PropertyInfo: {
      Name: "Ephratah",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Penthouse",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Farmland",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Every_6_Months",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment3.svg",
  otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/apartment2.svg",
      ],
    },
  },

  {
    _id: 14,
    PropertyInfo: {
      Name: "Bethel Homez",
      Title: "Title",
      State: "Lagos",
      ListingType: "Sale",
      Property_type: "Penthouse",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Quarterly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 15,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Mini flat",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Every_6_Months",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment1.svg",
      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 16,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Sale",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 1,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Yearly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment3.svg",
  otherPhotos: [
        "/static/images/house1.png",
        "/static/images/apartment2.svg",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 17,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Mini flat",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 10,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Yearly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment2.svg",
      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
  {
    _id: 18,
    PropertyInfo: {
      Name: "Adex Aosz",
      Title: "Title",
      State: "Lagos",
      ListingType: "Rent",
      Property_type: "Studio Apartment",
      Price: 106000,
      Area: "Yaba",
      Street: "Onike Street",
      Bedrooms: 7,
      Bathroom: 1,
      Toilets: 1,
      SquareMetres: 400,
      LandType:"Commercial",
      Description: "Great, awesome and cool place to be",
    },
    contactInfo: {
      PhoneNumber: "09056432765",
      Email: "pinky@estate.com",
      WhatsAppLink: "whatsapp+2349065432786",
    },
    RentalInfo: {
      Price: 2000000,
      maintenanceFee: 10000,
      totalFee: 150000,
      Payment_Type: "Quarterly",
      agencyFee: 25000,
    },
    Photos: {
      coverPhoto: "/static/images/apartment1.svg",
      otherPhotos: [
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
        "/static/images/house1.png",
        "/static/images/imageHouseHP.png",
        "/static/images/house2.png",
      ],
    },
  },
];
