"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";
import Header from "./components/admin_header";
import HeaderMobile from "./components/mobile_header";
import MarginWidthWrapper from "./components/margin-width-wrapper";
import PageWrapper from "./components/page-wrapper";
import SideNav from "./components/adminSideNav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [searchValue, setSearchValue] = useState("");

  return (
    <html lang="en">
      <body className=''>
      <div className="flex gap-3 md:gap-0">
      <SideNav />
      <main className="flex-1">
        <MarginWidthWrapper>
          <Header setSearchValue={setSearchValue} searchValue={searchValue} />
          <HeaderMobile setSearchValue={setSearchValue} />
          <PageWrapper>
            {children}
          </PageWrapper>
        </MarginWidthWrapper>
      </main>
    </div>
      </body>
    </html>
  );
}



// const inter = Inter({ subsets: ["latin"] });


// export default function RootLayout({ children}) {
//   const [searchValue, setSearchValue] = useState("");
//   // console.log(searchValue);
//   // params.search = searchValue;
//   return (
//     <div className="flex gap-3 md:gap-0">
//       <SideNav />
//       <main className="flex-1">
//         <MarginWidthWrapper>
//           <Header setSearchValue={setSearchValue} searchValue={searchValue} />
//           <HeaderMobile setSearchValue={setSearchValue} />
//           <PageWrapper>
//             {children}
//           </PageWrapper>
//         </MarginWidthWrapper>
//       </main>
//     </div>
//   );
// }
