// RootLayout.js
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "../../useReactQuery";

const plus_Jakarta_Sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, dehydratedState }) {
  return (
    <html lang="en">
      <body className={plus_Jakarta_Sans.className}>
        <ReactQueryProvider dehydratedState={dehydratedState}>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
