export const VisitorData = [
  {
    id: 1,
    TenantName: "Isaiah Gorge",
    VisitorName: "John Dare James John",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "-",
    Time_Out: "-",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 2,
    TenantName: "Chinyere Chioma",
    VisitorName: "John Dare Chioma Erra",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 3,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 4,
    TenantName: "Sunday Agbo",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 5,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 6,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 7,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 8,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 9,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 10,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 11,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 12,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 13,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 14,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 15,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 16,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 17,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 18,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 19,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 20,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 21,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 22,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 23,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 24,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 25,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 26,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 27,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 28,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed Out",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 29,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 30,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 31,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Signed In",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  {
    id: 32,
    TenantName: "Adeyemo Olayemi",
    VisitorName: "John Dare",
    Phone_Number: "000 0000 000",
    PurposeOfVisit: "Social visit",
    AccessStatus: "Pending",
    DateOfVisit: "4th January, 2024",
    AccessCode: "VictorKunle-3096",
    No_Of_Persons: "5",
    TimeIn: "2:05 PM",
    Time_Out: "5:05 PM",
    Property: "Sunrise Property",
    ApartmentNo: "Apartment1",
    Address: "17, Alapere, Alagomeji Area, Yaba, Lagos",
  },
  
 
];
