import React from 'react'

const Value = [
    {
      id: 1,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Confirmed",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
      id: 2,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Pending",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
      id: 3,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Confirmed",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
      id: 4,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Pending",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
      id: 5,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Pending",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
      id: 6,
      Date: "4th January, 2024",
      DueDate: "4th January, 2024",
      RentPaid: "N750,000",
      Status: "Pending",
      PropertyType: "4th January, 2024",
      Action: false,
    },
    {
        id: 7,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 8,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 9,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 10,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 11,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 12,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 13,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Confirmed",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 14,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 15,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Confirmed",
        PropertyType: "4th January, 2024",
        Action: false,
      },     {
        id: 16,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Pending",
        PropertyType: "4th January, 2024",
        Action: false,
      },
      {
        id: 17,
        Date: "4th January, 2024",
        DueDate: "4th January, 2024",
        RentPaid: "N750,000",
        Status: "Confirmed",
        PropertyType: "4th January, 2024",
        Action: false,
      },
  ];

export default Value;